apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: team-slo-results
  labels:
    app: team-slo-results
    app.kubernetes.io/component: team-slo-results
    app.kubernetes.io/instance: team-slo-results
    app.kubernetes.io/part-of: openshift-bugzilla-tools
