kind: Job
apiVersion: batch/v1
metadata:
  name: bug-automation
  labels:
    app: bug-automation
    type: oneshot
spec:
  template:
    metadata:
      labels:
        app: bug-automation
    spec:
      volumes:
        - name: bugzilla-api-key
          secret:
            secretName: bugzilla-api-key
            defaultMode: 420
      containers:
        - name: bug-automation
          image: 'quay.io/eparis/bug-automation:latest'
          resources: {}
          volumeMounts:
            - name: bugzilla-api-key
              readOnly: true
              mountPath: /etc/bugzilla
          imagePullPolicy: Always
      restartPolicy: OnFailure
