kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: docker-multistage
    app.openshift.io/vcs-uri: 'https://github.com/openshift/bugzilla-tools.git'
  name: redirect
  labels:
    app: redirect
    app.kubernetes.io/component: redirect
    app.kubernetes.io/instance: redirect
    app.kubernetes.io/part-of: openshift-bugzilla-tools
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'redirect:latest'
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfiles/Dockerfile.redirect
  source:
    type: Git
    git:
      uri: 'https://github.com/eparis/bugzilla-tools.git'
      ref: docker-multistage
    contextDir: /
  triggers:
    - type: ConfigChange
  runPolicy: Serial
