apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: blocker-slack
  labels:
    app: blocker-slack
    app.kubernetes.io/component: blocker-slack
    app.kubernetes.io/instance: blocker-slack
    app.kubernetes.io/part-of: openshift-bugzilla-tools
