apiVersion: apps/v1
kind: Deployment
metadata:
  name: blocker-slack
  annotations:
    app.openshift.io/vcs-ref: main
    app.openshift.io/vcs-uri: 'https://github.com/openshift/bugzilla-tools.git'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"blocker-slack:latest","namespace":"ocp-eng-architects"},"fieldPath":"spec.template.spec.containers[?(@.name==\"blocker-slack\")].image","pause":"false"}]
  labels:
    app: blocker-slack
    app.kubernetes.io/component: blocker-slack
    app.kubernetes.io/instance: blocker-slack
    app.kubernetes.io/part-of: openshift-bugzilla-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blocker-slack
  template:
    metadata:
      labels:
        app: blocker-slack
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/ocp-eng-architects/blocker-slack:latest
        imagePullPolicy: Always
        name: blocker-slack
        resources: {}
        volumeMounts:
        - name: slack-key
          readOnly: true
          mountPath: /etc/slack
        - name: bugzilla-api-key
          readOnly: true
          mountPath: /etc/bugzilla
        - name: blocker-slack-config
          readOnly: true
          mountPath: /etc/blocker-slack
      restartPolicy: Always
      volumes:
      - name: bugzilla-api-key
        secret:
          secretName: bugzilla-api-key
          defaultMode: 420
      - name: slack-key
        secret:
          secretName: slack-key
          defaultMode: 420
      - name: blocker-slack-config
        configMap:
          name: blocker-slack-config
          defaultMode: 420
