apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: 'https://github.com/openshift/bugzilla-tools.git'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"jira-daily-diff:latest","namespace":"ocp-eng-architects"},"fieldPath":"spec.template.spec.containers[?(@.name==\"jira-daily-diff\")].image","pause":"false"}]
  labels:
    app: jira-daily-diff
    app.kubernetes.io/component: jira-daily-diff
    app.kubernetes.io/instance: jira-daily-diff
    app.kubernetes.io/part-of: openshift-bugzilla-tools
  name: jira-daily-diff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jira-daily-diff
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
  template:
    metadata:
      labels:
        app: jira-daily-diff
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/ocp-eng-architects/jira-daily-diff:latest
        imagePullPolicy: Always
        name: jira-daily-diff
        resources: {}
        volumeMounts:
        - mountPath: /issues
          name: issues-pvc
        - mountPath: /etc/jira
          name: jira-key
          readOnly: true
        ports:
        - name: web
          containerPort: 8002
          protocol: TCP
      restartPolicy: Always
      volumes:
      - name: issues-pvc
        persistentVolumeClaim:
          claimName: jira-daily-diff-pvc
      - name: jira-key
        secret:
          defaultMode: 420
          secretName: jira-key
